name: Extract Google Scholar Data, Write to JSON, and Push JSON

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "extract-google-scholar-data"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-search-results

    - name: Run script using serapi secret to generate JSON
      run: |
        SERP_SECRET=${{ secrets.SERP_API_KEY }} python .github/workflows/serpiapi.py
      env:
          SERAPI_KEY: ${{ secrets.SERP_API_KEY }}

    - name: Verify JSON file creation
      run: |
        ls -l data/json
        cat data/json/googlescholar_output.json

    - name: Check if JSON file has changed
      id: check_changes
      run: |
        git fetch origin main
        git diff --exit-code --quiet origin/main data/json/googlescholar_output.json || echo "changed=true" >> $GITHUB_ENV

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push JSON file
      if: env.changed == 'true'
      run: |
        git add data/json/googlescholar_output.json
        git commit -m 'Update generated JSON file'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}